changelog:
  categories:
    - title: "✨ New Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🛠 Improvements & Maintenance"
      labels:
        - "refactor"
        - "maintenance"
        - "chore"
    - title: "📖 Documentation Updates"
      labels:
        - "documentation"
        - "docs"
    - title: "⚡️ Performance Improvements"
      labels:
        - "performance"
    - title: "📦 Dependency Updates"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"